apiVersion: apps/v1
kind: Deployment
metadata:
  name: MovieDatabase
  labels:
    app: MovieDatabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MovieDatabase
  template:
    metadata:
      labels:
        app: MovieDatabase
    spec:
      containers:
        - name: MovieDatabase
          image: ghcr.io/shaikimtiazali/moviedatabase:sha-a4a1dfcc2e97f860505f67f904288559212a9210
          imagePullPolicy: Always
          ports:
            - containerPort: 80
        - resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2" 
              memory: "256Mi"
          livelinessProbe:
            httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          readinessProbe:
          httpGet: /
          port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
        - name: github-container-registry