apiVersion: apps/v1
kind: Deployment
metadata:
  name: Moviedatabase
  labels:
    app: Moviedatabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Moviedatabase
  template:
    metadata:
      labels:
        app: Moviedatabase
    spec:
      containers:
        - name: Moviedatabase
          image: ghcr.io/shaikimtiazali/moviedatabase:sha-dca3de49b6bf4fc8aff150b9fef94085c43975f0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
        - resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2" 
              memory: "256Mi"
          livelinessProbe:
            httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          readinessProbe:
          httpGet: /
          port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
        - name: github-container-registry
